### ISSUE TITLE
CapsLock Problem

### ISSUE THREAD

**Issue by gaojingqi23** [tobozo/ESP32-USB-Soft-Host#28]
It's exciting when the lcd appeared what i type by keyboard, but then i found a problem about CapsLock. I could change CapsLock state only once. Through some debug, i solved this problem. Now i can change CapsLock state just as i wish.
Origin Code(usbkbd.h):
```cpp
virtual uint8_t HandleLockingKeys(uint8_t key)
    {
      switch(key) {
        case UHS_HID_BOOT_KEY_NUM_LOCK:
          bmNumLock = ~bmNumLock;
        break;
        case UHS_HID_BOOT_KEY_CAPS_LOCK:
          bmCapsLock = ~bmCapsLock;
          //Serial.printf("CapsLock Changed.CapsLock:%d\n",bmCapsLock);
        break;
        case UHS_HID_BOOT_KEY_SCROLL_LOCK:
          bmScrollLock = ~bmScrollLock;
        break;
      }
      return 0;
    };
```
Modified Code:
```cpp
 virtual uint8_t HandleLockingKeys(uint8_t key)
    {
      switch(key) {
        case UHS_HID_BOOT_KEY_NUM_LOCK:
          bmNumLock = !bmNumLock;
        break;
        case UHS_HID_BOOT_KEY_CAPS_LOCK:
          bmCapsLock = !bmCapsLock;
          //Serial.printf("CapsLock Changed.CapsLock:%d\n",bmCapsLock);
        break;
        case UHS_HID_BOOT_KEY_SCROLL_LOCK:
          bmScrollLock = !bmScrollLock;
        break;
      }
      return 0;
    };
```
Just change a operator from ~ to !.

**Comment by tobozo** [comment]
hey @gaojingqi23, thanks for your feedback!

The suggested fix is now applied to the main branch of this repository.

The keyboard test sketch was inspired from the [USB-Host-Shield KeyboardParser example](https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/Bluetooth/BTHID/KeyboardParser.h#L16). 

Same error was fixed in august, different folder : [examples/USB_Test/usbkbd.h](https://github.com/tobozo/ESP32-USB-Soft-Host/commit/edc52814e7afa97db75c5e8f559f859cd954fa8f#diff-98e16711d8d250f5f34531286151eaa652236cda08b1a8daa0cecb7c4c1b7051), looks like I forgot to fix the M5Stack example too :blush: 

Thanks again for reporting this!

Closing this issue as solved.
